// servers/ssr/src/components/Home.tsx
/**
 * 首页组件
 */
import React, { useEffect } from 'react';
import { useAppState, useAppDispatch } from '../shared/store';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

const Home: React.FC = () => {
  const { pageData, loading } = useAppState();
  const dispatch = useAppDispatch();
  const data = pageData['/'] || {};

  useEffect(() => {
    // 客户端数据获取
    if (!data.title) {
      dispatch({ type: 'SET_LOADING', payload: true });

      fetch('/api/home')
        .then(res => res.json())
        .then(data => {
          dispatch({
            type: 'SET_PAGE_DATA',
            payload: { '/': data }
          });
          dispatch({ type: 'SET_LOADING', payload: false });
        })
        .catch(error => {
          console.error('获取数据失败:', error);
          dispatch({ type: 'SET_ERROR', payload: error });
          dispatch({ type: 'SET_LOADING', payload: false });
        });
    }
  }, [data.title, dispatch]);

  return (
    <div className="home-page">
      <Helmet>
        <title>{data.title || 'React 19 SSR 演示'}</title>
        <meta name="description" content={data.description || 'React 19 SSR 演示首页'} />
      </Helmet>

      <header className="header">
        <div className="container">
          <h1>{data.title || 'React 19 SSR 演示'}</h1>
          <p className="subtitle">{data.subtitle || '使用React 19、Koa和TypeScript实现的高性能SSR应用'}</p>
        </div>
      </header>

      <main className="main">
        <div className="container">
          {loading ? (
            <div className="loading">加载中...</div>
          ) : (
            <>
              <section className="features">
                <h2>主要特性</h2>
                <div className="feature-grid">
                  <div className="feature-item">
                    <h3>React 19 流式SSR</h3>
                    <p>利用React 19的最新流式渲染功能，实现更快的首屏加载和更好的用户体验。</p>
                  </div>
                  <div className="feature-item">
                    <h3>高性能Koa服务器</h3>
                    <p>基于Koa构建的高性能服务器，支持集群模式和多级缓存策略。</p>
                  </div>
                  <div className="feature-item">
                    <h3>TypeScript支持</h3>
                    <p>全栈TypeScript支持，提供类型安全和更好的开发体验。</p>
                  </div>
                  <div className="feature-item">
                    <h3>多级缓存</h3>
                    <p>实现页面级、组件级和数据级缓存，显著提升性能。</p>
                  </div>
                </div>
              </section>

              <section className="cta">
                <h2>开始使用</h2>
                <p>立即体验React 19的强大SSR功能</p>
                <div className="buttons">
                  <Link to="/about" className="button primary">了解更多</Link>
                  <a href="https://github.com" className="button secondary" target="_blank" rel="noopener noreferrer">查看源码</a>
                </div>
              </section>
            </>
          )}
        </div>
      </main>

      <footer className="footer">
        <div className="container">
          <p>&copy; {new Date().getFullYear()} React 19 SSR 演示</p>
        </div>
      </footer>

      <style jsx>{`
        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 20px;
        }

        .header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 80px 0;
          text-align: center;
        }

        .header h1 {
          font-size: 3rem;
          margin-bottom: 1rem;
        }

        .subtitle {
          font-size: 1.5rem;
          opacity: 0.9;
        }

        .main {
          padding: 60px 0;
        }

        .features {
          margin-bottom: 60px;
        }

        .features h2 {
          text-align: center;
          margin-bottom: 40px;
          font-size: 2rem;
        }

        .feature-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 30px;
        }

        .feature-item {
          background: #f8f9fa;
          padding: 30px;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }

        .feature-item h3 {
          margin-top: 0;
          color: #4a5568;
        }

        .cta {
          text-align: center;
          background: #f1f5f9;
          padding: 60px 30px;
          border-radius: 12px;
        }

        .cta h2 {
          font-size: 2rem;
          margin-bottom: 1rem;
        }

        .buttons {
          margin-top: 30px;
          display: flex;
          justify-content: center;
          gap: 20px;
        }

        .button {
          display: inline-block;
          padding: 12px 24px;
          border-radius: 6px;
          font-weight: 600;
          text-decoration: none;
          transition: all 0.3s ease;
        }

        .button.primary {
          background: #4f46e5;
          color: white;
        }

        .button.primary:hover {
          background: #4338ca;
        }

        .button.secondary {
          background: white;
          color: #4f46e5;
          border: 1px solid #4f46e5;
        }

        .button.secondary:hover {
          background: #f9fafb;
        }

        .footer {
          background: #1e293b;
          color: white;
          padding: 30px 0;
          text-align: center;
        }

        .loading {
          text-align: center;
          padding: 40px;
          font-size: 1.5rem;
          color: #a0aec0;
        }
      `}</style>
    </div>
  );
};

export default Home;

// vue-app/vite-vue-ts/src/views/Home/index.vue
<script setup lang="ts">
import { useHome } from './Home'

const { features, navigateTo } = useHome()
</script>

<template>
  <div class="home-container">
    <section class="hero">
      <h1>Vue3 学习平台</h1>
      <p class="subtitle">深入学习Vue3的核心特性和最佳实践</p>
      <div class="cta-buttons">
        <button class="primary-btn" @click="navigateTo('/vue3/composition-api')">
          开始学习
        </button>
        <button class="secondary-btn" @click="navigateTo('/playground')">
          在线编辑器
        </button>
      </div>
    </section>

    <section class="features">
      <h2>核心特性</h2>
      <div class="feature-grid">
        <div
          v-for="feature in features"
          :key="feature.title"
          class="feature-card"
          @click="navigateTo(feature.path)"
        >
          <div class="feature-icon">{{ feature.icon }}</div>
          <h3>{{ feature.title }}</h3>
          <p>{{ feature.description }}</p>
        </div>
      </div>
    </section>

    <section class="why-vue3">
      <h2>为什么选择Vue3?</h2>
      <div class="benefits">
        <div class="benefit">
          <h3>🚀 更好的性能</h3>
          <p>Vue3的虚拟DOM重写和编译优化使渲染速度提升高达100%</p>
        </div>
        <div class="benefit">
          <h3>📦 更小的体积</h3>
          <p>核心运行时压缩后仅10kb，支持按需引入</p>
        </div>
        <div class="benefit">
          <h3>🛠️ 更强的TypeScript支持</h3>
          <p>从底层重写，提供完整的类型推导</p>
        </div>
        <div class="benefit">
          <h3>🧩 组合式API</h3>
          <p>更灵活的逻辑组织和复用方式</p>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.home-container {
  max-width: 1200px;
  margin: 0 auto;
}

.hero {
  text-align: center;
  padding: 3rem 1rem;
  margin-bottom: 2rem;
}

.hero h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
  color: #42b883;
}

.subtitle {
  font-size: 1.5rem;
  color: var(--text-color);
  margin-bottom: 2rem;
  opacity: 0.8;
}

.cta-buttons {
  display: flex;
  gap: 1rem;
  justify-content: center;
}

.primary-btn, .secondary-btn {
  padding: 0.75rem 1.5rem;
  border-radius: 4px;
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.primary-btn {
  background-color: #42b883;
  color: white;
  border: none;
}

.primary-btn:hover {
  background-color: #3ca576;
}

.secondary-btn {
  background-color: transparent;
  border: 1px solid #42b883;
  color: #42b883;
}

.secondary-btn:hover {
  background-color: rgba(66, 184, 131, 0.1);
}

.features, .why-vue3 {
  margin-bottom: 3rem;
}

.features h2, .why-vue3 h2 {
  text-align: center;
  margin-bottom: 2rem;
  color: var(--text-color);
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 1.5rem;
}

.feature-card {
  background-color: var(--header-bg);
  border-radius: 8px;
  padding: 1.5rem;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
}

.feature-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 8px 15px rgba(0, 0, 0, 0.1);
}

.feature-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

.feature-card h3 {
  margin-bottom: 0.5rem;
  color: #42b883;
}

.feature-card p {
  color: var(--text-color);
  opacity: 0.8;
}

.benefits {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 1.5rem;
}

.benefit {
  padding: 1.5rem;
  border-radius: 8px;
  background-color: var(--header-bg);
}

.benefit h3 {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: #42b883;
  margin-bottom: 0.5rem;
}

.benefit p {
  color: var(--text-color);
  opacity: 0.8;
}
</style>
